services:
  frontend:
    build:
      context: .
      args:
        ENV: local
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
    ports:
      - "8080:80"
    env_file: .env.development
    depends_on:
      - ai-slop

  ai-slop:
    build:
      context: .
      dockerfile: ./ai-slop/AI-Slop-For-CAO-exam/Dockerfile
      args:
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
    ports:
      - "8081:80"
    env_file: .env.development